// Shared Clerk appearance config for sign-in and sign-up pages
export const clerkAppearance = {
  variables: {
    colorPrimary: "#4CAF50",
    colorBackground: "#2A2A3E",
    colorText: "#C0C0D0",
    colorTextSecondary: "#D0D0E0",
    colorInputBackground: "#0A0A14",
    colorInputText: "#E8E8E8",
    colorNeutral: "#C0C0D0",
    borderRadius: "0px",
    fontFamily: "monospace",
    fontSize: "12px",
  },
  elements: {
    rootBox: "mx-auto",
    card: {
      backgroundColor: "#2A2A3E",
      border: "4px solid #5A5A7A",
      boxShadow: "8px 8px 0 0 rgba(0,0,0,0.3)",
      borderRadius: "0px",
    },
    headerTitle: {
      fontFamily: '"Press Start 2P", monospace',
      color: "#FFD700",
      fontSize: "10px",
    },
    headerSubtitle: {
      color: "#9090A0",
      fontSize: "11px",
      fontFamily: "monospace",
    },
    socialButtonsBlockButton: {
      backgroundColor: "#1A1A2E",
      border: "2px solid #5A5A7A",
      borderRadius: "0px",
    },
    socialButtonsBlockButtonText: {
      color: "#E8E8E8",
      fontSize: "10px",
      fontFamily: "monospace",
    },
    dividerLine: {
      backgroundColor: "#5A5A7A",
    },
    dividerText: {
      color: "#9090A0",
      fontSize: "10px",
    },
    formFieldLabel: {
      color: "#C0C0D0",
      fontSize: "10px",
      fontFamily: "monospace",
      textTransform: "uppercase" as const,
      letterSpacing: "0.05em",
    },
    formFieldInput: {
      backgroundColor: "#0A0A14",
      border: "2px solid #5A5A7A",
      borderRadius: "0px",
      color: "#E8E8E8",
      fontSize: "12px",
      fontFamily: "monospace",
    },
    formButtonPrimary: {
      backgroundColor: "#4CAF50",
      borderRadius: "0px",
      border: "none",
      boxShadow: "0 4px 0 0 #388E3C",
      color: "#0A0A14",
      fontSize: "10px",
      fontFamily: "monospace",
      fontWeight: "700",
      textTransform: "uppercase" as const,
      letterSpacing: "0.05em",
    },
    footerActionLink: {
      color: "#FFD700",
      fontSize: "10px",
      fontFamily: "monospace",
    },
    footerActionText: {
      color: "#9090A0",
      fontSize: "10px",
      fontFamily: "monospace",
    },
    footer: {
      color: "#D0D0E0",
      fontSize: "10px",
      fontFamily: "monospace",
    },
    footerPages: { color: "#D0D0E0" },
    footerPagesLink: { color: "#D0D0E0" },
    identityPreviewEditButton: { color: "#FFD700" },
    formFieldAction: { color: "#FFD700", fontSize: "10px" },
    alertText: { color: "#E74C3C", fontSize: "10px" },
    formFieldWarningText: { color: "#E74C3C", fontSize: "10px", fontFamily: "monospace" },
    formFieldSuccessText: { color: "#66BB6A", fontSize: "10px", fontFamily: "monospace" },
    formFieldErrorText: { color: "#E74C3C", fontSize: "10px", fontFamily: "monospace" },
    formFieldInfoText: { color: "#66BB6A", fontSize: "10px", fontFamily: "monospace" },
    footerAction: { color: "#D0D0E0" },
    badge: { color: "#D0D0E0" },
    poweredBy: { color: "#D0D0E0" },
  },
  layout: {
    unsafe_disableDevelopmentModeWarnings: true,
  },
} as const;
